import motion from '../public/assets/motion/manifest.json';
import animated from '../public/assets/animated/manifest.json';
import campaignImages from '../public/assets/campaign/responsive.json';

const characterAnimations = animated.filter(item => !item.adult);
const adultAnimations = animated.filter(item => item.adult);
// Temporarily unpublished; keep the section and its media for later restoration.
const SHOW_ADULT_PREVIEWS = false;

const picture = (name, alt, caption='', eager=false) => {
  const sizes = campaignImages[name];
  return `<figure class="campaign ${name === 'poster' ? 'poster-art' : ''}"><img src="${sizes['480'].src}" srcset="${sizes['480'].src} 480w, ${sizes['960'].src} 960w" sizes="(max-width: 760px) calc(100vw - 48px), (max-width: 1280px) 45vw, 560px" alt="${alt}" width="1254" height="1254" ${eager?'fetchpriority="high" loading="eager"':'loading="lazy"'} decoding="async">${caption?`<figcaption>${caption}</figcaption>`:''}</figure>`;
};
const controls = `<div class="gallery-controls"><span>Swipe to explore <span aria-hidden="true">↔</span></span><div><button data-gallery-prev aria-label="Previous examples">←</button><button data-gallery-toggle aria-label="Pause automatic scrolling">Pause scroll</button><button data-gallery-next aria-label="Next examples">→</button></div></div>`;
const motionGallery = `<div data-gallery class="gallery motion-gallery" aria-label="AI motion references">${controls}<div class="gallery-track" tabindex="0" aria-label="Scrollable motion examples">${motion.map((item,i)=>`<figure class="motion-card" data-animated-media><video data-loop-src="${item.video}" data-poster="${item.poster}" aria-label="${item.label}" preload="none" muted loop playsinline width="400" height="693"></video><figcaption><span>SCENE ${String(i+1).padStart(2,'0')}</span><span>${Math.round(item.duration)}s ↗</span></figcaption></figure>`).join('')}</div></div>`;
const animation = (id, cls='animation-inset', controls=true) => {
  const item = animated.find(item=>item.id===id);
  if (!item) return '';
  return `<figure class="${cls}" data-animated-media><video data-loop-src="${item.video}" data-poster="${item.poster}" aria-label="AI character animation ${id.replace('video-','')}" width="${item.width}" height="${item.height}" muted loop playsinline preload="none"></video>${controls?'<button type="button" data-motion-toggle aria-label="Pause animation">Pause animation</button>':''}<figcaption>IN MOTION <span aria-hidden="true">✦</span></figcaption></figure>`;
};
const campaignClips = {hero:'video-01',poster:'video-06',expression:'video-04',imagination:'video-10',workflow:'video-05',movement:'video-07',curriculum:'video-08',prompts:'video-09',offer:'video-03',final:'video-02'};
const campaignMotion = (name,alt,caption='',eager=false) => `<div class="motion-composition">${picture(name,alt,caption,eager)}${animation(campaignClips[name])}</div>`;
const characterGallery = (items, adult=false) => `<div data-gallery class="gallery inspiration-gallery" aria-label="${adult?'Adult animation gallery':'Animated character gallery'}">${controls}<div class="gallery-track" tabindex="0" aria-label="${adult?'Scrollable adult animation examples':'Scrollable animated character examples'}">${items.map((item,i)=>`<figure class="inspiration-card animated-card${adult?' adult-preview':''}" data-animated-media><video data-loop-src="${item.video}" data-poster="${item.poster}" aria-label="${adult?'Adult animation preview':'AI character animation'} ${i+1}" width="${item.width}" height="${item.height}" muted loop playsinline preload="none"></video><figcaption>${adult?'18+ PREVIEW':'CHARACTER IN MOTION'} ${String(i+1).padStart(2,'0')}</figcaption></figure>`).join('')}</div></div>`;
const extraGallery = characterGallery(characterAnimations);
const adultGallery = characterGallery(adultAnimations, true);
const motionTrio = (...ids) => `<div class="motion-duo motion-trio">${ids.map(id=>animation(id,'standalone-animation')).join('')}</div>`;
const motionDuo = (first,second) => `<div class="motion-duo">${animation(first,'standalone-animation')}${animation(second,'standalone-animation')}</div>`;

export function createLanding({brand,cta,footer,modules,faq}) { return `
<div class="announcement"><span>YOUR IMAGINATION. IN MOTION.</span><a href="#offer">$9.99 once · Lifetime course access ↗</a></div>
<header class="header wrap">${brand}<nav aria-label="Main"><a href="#showcase">The possibilities</a><a href="#curriculum">Inside the course</a><a href="#faq">FAQ</a></nav><button class="header-cta" data-checkout>Get access · $9.99 ↗</button></header>
<main>
<section class="hero wrap" id="top"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> ULTIMATE AI VIDEO MASTERY</p><h1>Wild AI videos.<br><em>Beyond your own<br>imagination.</em></h1><p class="hero-desc">Learn to create wild AI videos beyond your own imagination. Dream up captivating characters, seductive moods and cinematic worlds — then learn to bring them to life, one scene at a time.</p><div class="hero-actions">${cta('Unlock lifetime access · $9.99')}<a class="watch-link" href="#showcase">Explore the motion gallery ↓</a></div><p class="purchase-note">Pay once. Keep the course. Create at your own pace.</p><div class="hero-facts"><span><b>12</b> practical modules</span><span><b>100</b> editable prompts</span><span><b>∞</b> creative ideas</span></div></div><div class="hero-visual">${campaignMotion('hero','AI-created brunette character pointing toward the viewer in a purple-lit studio','AI-created campaign imagery',true)}<div class="hero-stamp"><span>FROM IMAGINATION</span><strong>to “I made that.”</strong><span>YOUR NEXT CREATIVE OBSESSION ↗</span></div></div></section>
<div class="feature-strip"><span>✦ GLAMOUR</span><span>✦ EXPRESSION</span><span>✦ FANTASY</span><span>✦ MOVEMENT</span><span>✦ CINEMATIC WORLDS</span></div>
<section class="section wrap split intro"><div><p class="eyebrow">01 / THINK A LITTLE WILDER</p><h2>You imagine her.<br>You set the scene.<br><em>You direct the moment.</em></h2><p>A knowing glance. A playful gesture. A confident walk through a neon city. Your own character, stepping into a world you dreamed up.</p><p>We’ll show you how to turn that idea into a clear visual brief, choose the right starting image and direct the movement. Give your imagination a process you can actually use.</p>${cta('I’m ready to create')}</div>${campaignMotion('poster','Ultimate AI Video Mastery purple campaign poster','Your course. Your creative starting point.')}</section>
<section class="showcase section" id="showcase"><div class="wrap"><div class="section-head"><div><p class="eyebrow">02 / IMAGINE THE POSSIBILITIES</p><h2>Pretty is a start.<br><em>Presence is everything.</em></h2></div><p>${motion.length} motion references. Expressions, gestures and character performance. Keep swiping — there’s more than one way to bring an avatar to life.</p></div>${motionGallery}<p class="caption">Motion references from the original course. Results depend on your image, model and direction.</p></div></section>
<section class="inspiration section" id="characters"><div class="wrap"><div class="section-head"><div><p class="eyebrow">YOUR NEXT CHARACTER STARTS HERE</p><h2>One imagination.<br><em>A whole cast of possibilities.</em></h2></div><p>Explore ${characterAnimations.length} animated characters. A new look, a new attitude, a whole new scene. Swipe through and find the spark for your next creation.</p></div>${extraGallery}<p class="caption">Keep exploring. These AI characters keep moving while you swipe or pause the automatic scroll.</p></div></section>
${SHOW_ADULT_PREVIEWS ? `<section class="adult-showcase section" id="adult-previews" aria-labelledby="adult-preview-title"><div class="wrap"><div class="section-head"><div><p class="eyebrow adult-section-label"><span class="age-badge">18+</span> ADULT AI SHOWCASE</p><h2 id="adult-preview-title">Beyond your<br><em>wildest imagination.</em></h2></div><div class="adult-section-copy"><p>Inside Mastery, learn the image-to-video skills to take your ideas further: prepare your starting image, direct expression and movement, shape camera and light, then review and refine your clips.</p><p class="adult-content-note">This separate gallery contains ${adultAnimations.length} adult AI previews with explicit content. For viewers aged 18 and over.</p></div></div>${adultGallery}<p class="caption">Owner-supplied AI examples. The course teaches general image-to-video techniques; explicit scene tutorials are not included. Results vary with your inputs and generation platform.</p></div></section>` : ''}
<section class="section wrap split"><div>${campaignMotion('expression','AI-created adult character making a playful peace gesture')}</div><div><p class="eyebrow">03 / YOU HAVE THE IDEA. NOW WHAT?</p><h2>Less random output.<br><em>More of your vision.</em></h2><div class="problem-list"><article><span>01</span><div><h3>She looks different in every frame.</h3><p>Learn what helps preserve identity, expression and detail.</p></div></article><article><span>02</span><div><h3>The movement kills the mood.</h3><p>Direct one clear action, with expression and timing that support it.</p></div></article><article><span>03</span><div><h3>Another attempt. More credits gone.</h3><p>Review what failed and refine deliberately, instead of guessing again.</p></div></article></div></div></section>
<section class="tinted section"><div class="wrap split"><div><p class="eyebrow">04 / YOUR IDEAS DESERVE A BIGGER WORLD</p><h2>Go glamorous.<br>Go cinematic.<br><em>Go wonderfully wild.</em></h2><p>Create original virtual muses. Explore fashion, fantasy and expressive character stories. Build an aesthetic that feels unmistakably yours.</p><p>This is a practical course in creative direction: the source image, the prompt, the performance and the decisions that bring a scene together.</p><div class="inline-tags"><span>YOUR CHARACTER</span><span>YOUR WORLD</span><span>YOUR STYLE</span></div>${cta('Unlock my creative playbook')}</div>${campaignMotion('imagination','AI-created fantasy queen wearing an ornate golden crown and evening costume')}</div></section>
<section class="section wrap split"><div>${campaignMotion('workflow','AI-created creator wearing glasses and headphones in a purple studio')}</div><div><p class="eyebrow">05 / FROM “WHAT IF” TO YOUR FIRST CLIP</p><h2>Imagine it.<br>Direct it.<br><em>Make it move.</em></h2><div class="steps">${[['01','Create your starting point','Choose your character, style, setting and source image.'],['02','Write the moment','Build a prompt around action, expression, camera and timing.'],['03','Bring it together','Generate, review and improve. Edit your strongest takes into a finished sequence.']].map(([n,t,d])=>`<article><span>${n}</span><div><h3>${t}</h3><p>${d}</p></div></article>`).join('')}</div><p class="small">No coding required. Clear written steps and practical exercises you can return to.</p></div></section>
<section class="section wrap split"><div><p class="eyebrow">06 / LEARN TO DIRECT THE DETAILS</p><h2>The look.<br>The attitude.<br><em>The whole feeling.</em></h2><div class="outcome-grid">${[['Expression','Eye contact, mood and playful personality.'],['Movement','Gestures, poses, walking and rhythmic motion.'],['Atmosphere','Camera, lighting and cinematic settings.'],['Consistency','A recognisable character across your sequence.']].map(([t,d])=>`<article><h3>${t}</h3><p>${d}</p></article>`).join('')}</div>${cta('Give my ideas a direction')}</div>${campaignMotion('movement','AI-created adult character in a pink top looking over her shoulder')}</section>
<section class="tinted section" id="curriculum"><div class="wrap curriculum"><div class="curriculum-intro"><p class="eyebrow">07 / INSIDE YOUR LIFETIME ACCESS</p><h2>Your creative<br><em>playbook, unlocked.</em></h2><p>12 practical written modules in English. Follow the path from your first avatar image to a finished three-shot video.</p>${campaignMotion('curriculum','AI-created brunette character with a playful expression','Learn at your pace. Revisit whenever you need.')}</div><div><div class="format-note"><b>READ. APPLY. CREATE.</b><p>A self-paced written course with exercises and editable prompts. No recorded video lessons. Everything organised in one online learning hub.</p></div><div class="module-list">${modules.map(([t,d],i)=>`<details ${i===0?'open':''}><summary><span>${String(i+1).padStart(2,'0')}</span><h3>${t}</h3><b>+</b></summary><p>${d}</p></details>`).join('')}</div></div></div></section>
<section class="section wrap split"><div>${campaignMotion('prompts','AI-created adult character in a pink hooded outfit')}</div><div><p class="eyebrow">08 / THE BONUS THAT GETS YOU STARTED</p><h2>Big imagination.<br>Blank prompt box?<br><em>We’ve got you.</em></h2><p>Start with 100 editable motion prompt templates. Change the character, expression, action and scene to make each idea your own.</p><div class="prompt-library"><div class="library-top"><span>YOUR MOTION<br>PROMPT LIBRARY</span><b>100</b></div>${['Expression & eye contact','Poses & confident gestures','Dance & rhythmic movement','Fashion & character performance','Cinematic camera direction'].map(t=>`<div><span>✦</span><p>${t}</p><b>↗</b></div>`).join('')}</div><p class="small">Adaptable starting points, with guidance for experimenting and refining.</p></div></section>
<section class="audience section"><div class="wrap split"><div><p class="eyebrow">09 / FOR THE IDEAS YOU CAN’T STOP THINKING ABOUT</p><h2>Bring the curiosity.<br><em>Build the creative control.</em></h2><div class="audience-grid"><p class="check">Create your own original virtual muse.</p><p class="check">Explore glamour, fashion and fantasy.</p><p class="check">Build expressive characters and stories.</p><p class="check">Understand the process behind the prompt.</p></div><p class="small">For adults 18+. Bring original characters or images you have permission to use. Expect to experiment, practise and improve.</p></div>${motionDuo('video-18','video-20')}</div></section>
<section class="offer section" id="offer"><div class="wrap offer-grid"><div><p class="eyebrow">10 / ONE PAYMENT. A NEW CREATIVE SKILL.</p><h2>Pay once.<br>Keep the course.<br><em>Imagine what’s next.</em></h2>${campaignMotion('offer','AI-created red-haired adult character in a purple-lit studio')}</div><div class="price-card"><div class="price-card-top"><span>ULTIMATE AI VIDEO MASTERY</span><span>GLOBAL EDITION</span></div><div class="lifetime-pill">✦ LIFETIME COURSE ACCESS</div><h3>Your entire creative playbook</h3><div class="regular-price" data-promo-only hidden><span>Regular price <del>US$19.99</del></span><b>SAVE US$10</b></div><div class="price"><small>US</small>$9.99<span>USD<br>paid once</span></div><div class="offer-countdown" data-promo-only hidden><span>Your 5-hour welcome offer ends in</span><strong data-promo-countdown>--:--:--</strong><small>Reserved for this browser. Regular price US$19.99 after the timer ends.</small></div><p class="price-promise">No monthly course fees.<br>No annual renewals. It’s yours to revisit.</p><ul><li>12 practical written modules in English</li><li>100 editable motion prompt templates</li><li>Quickstart workflow & selection guide</li><li>Troubleshooting & finishing checklists</li><li>A practical three-shot final project</li><li>Immediate access after confirmed payment</li><li>Lifetime access to purchased course materials</li></ul>${cta('Yes — unlock my lifetime access','full')}<div class="payment-trust"><span>SECURE CHECKOUT</span><b><i>Pay</i>Pal</b><span>$9.99 ONCE</span></div><p class="price-disclosure">Your payment covers the course and templates. AI apps, subscriptions and generation credits are separate.</p></div></div></section>
<div class="purchase-clarity wrap"><span>∞</span><div><h3>One purchase. Keep coming back.</h3><p>Lifetime access to your purchased materials. If the learning hub moves, we’ll provide replacement access or an equivalent downloadable copy.</p></div></div>
<section class="section wrap faq" id="faq"><div><p class="eyebrow">11 / BEFORE YOU JUMP IN</p><h2>A little clarity.<br><em>Then let’s create.</em></h2><p class="support-contact">Need help?<br><a href="mailto:achaer31@gmail.com">Email: achaer31@gmail.com ↗</a><br><a href="https://t.me/ItsMrAofficial" target="_blank" rel="noopener noreferrer">Telegram: @ItsMrAofficial ↗</a></p>${motionTrio('video-05','video-15','video-10')}</div><div>${faq.map(([q,a])=>`<details><summary>${q}<b>+</b></summary><p>${a}</p></details>`).join('')}</div></section>
<section class="final-cta section"><div class="wrap split"><div>${campaignMotion('final','AI-created blonde character wearing headphones and making a peace gesture')}</div><div><p class="eyebrow">12 / YOUR NEXT CREATIVE OBSESSION</p><h2>You’ve imagined it.<br><em>Now learn to<br>bring it to life.</em></h2><p>Learn to create wild AI videos that take your imagination further. Your characters. Your stories. Your next “I never thought I could make that” moment.</p>${cta('Start creating · $9.99 for life')}<p class="purchase-note">12 written modules · 100 prompts · Lifetime course access</p></div></div></section>
</main>${footer()}<div class="mobile-buy"><div><b><span class="price-currency">US</span>$9.99 <span class="price-frequency">once</span></b><small>Lifetime course access</small></div><button data-checkout>Unlock access ↗</button></div>`; }

export function createCatalog({brand,footer}) { return `<div class="announcement">BIG IDEAS START WITH A NEW SKILL.</div><header class="header wrap">${brand}<a class="small-link" href="/ultimatevideoaimastery/access">My course access ↗</a></header><main class="catalog wrap"><p class="eyebrow">THE FORMUMAX LABS COLLECTION</p><h1>Learn something new.<br><em>Make something yours.</em></h1><p class="catalog-intro">Practical digital courses for curious creators, wherever you are. Explore our first global edition.</p><a href="/ultimatevideoaimastery" class="course-card">${picture('poster','Ultimate AI Video Mastery course cover','',true)}<div><span class="eyebrow">CREATIVE AI · GLOBAL EDITION</span><h2>Ultimate AI<br>Video Mastery</h2><p>Turn your visual imagination into expressive AI characters and cinematic videos. 12 written modules, 100 editable prompts, one clear creative workflow.</p><div class="catalog-price"><b><span class="price-currency">US</span>$9.99</b><span>One payment<br>Lifetime course access</span></div><span class="button primary">Explore the course ↗</span></div></a></main>${footer()}`; }
